### ISSUE TITLE
User can view a list of exercises

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#1]
## 💰 Feature

User can view a list of exercises

## 🗒️ Notes

This will require me to use fetch and react to render a list of exercises from the database

## 🖼 Wireframe

![View-exercises-list](https://user-images.githubusercontent.com/68713535/102934623-5f810080-4459-11eb-938f-53730c2557a5.png)

## ✅ Tasks

- [x] Add data schema to schema.sql
- [x] Add some exercise and muscle group data to data.sql
- [x] Create a route in `server/index.js` to handle GET requests at `/api/exercises`.
- [x] Test the route with HTTPie.
- [x] create an error middleware file that handles unexpected 500 errors
- [x] test error with HTTPie
- [x] style header and background using html css and bootstrap
- [x] Draw up layout in html and css
- [x] Define a component that renders the exercise list screen as shown in the wireframe but with no behavior.
- [x] Refactor the component to fetch the data from the server.
