### ISSUE TITLE
User can favorite and exercise

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#10]
## 💰 Feature

User can add an exercise to a favorites list

## 🗒️ Notes

User can add to favorites from exercise list.
This will require me to use click events, database.

## 🖼 Wireframe

![add-to-favorites](https://user-images.githubusercontent.com/68713535/102943157-171f0e00-446c-11eb-82ff-2751665485dc.png)

## ✅ Tasks

- [x] Create a new route in the server that handles post requests to the favorites table
- [x] Test with HTTPie
- [x] Add a favorites button to the exercise list on the front end
- [x] Add a click handler for the add to favorites button that sends the post request to the server
- [x] Fix double add bug
- [x] Add a route to the server that handles get requests to the favorites table. Test with HTTPie.
- [x] Add fetch request to favorites list in component did mount method on exercise list component and save favorites to state.
- [x] Fix text content based on favorites list
