### ISSUE TITLE
User can view favorite exercises

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#11]
## 💰 Feature

User can view favorite exercises

## 🗒️ Notes

User can view favorites list from profile

## 🖼 Wireframe

![favorites-from-profile](https://user-images.githubusercontent.com/68713535/102943672-8b0de600-446d-11eb-9d57-621b79b7ba11.png)

## ✅ Tasks
- [x] Create a route in index.js that handles get requests for the favorites list
- [x] Test with HTTPie
- [x] Add button to front end on profile page that takes the user to a favorites page
- [x] Create a component that renders an empty favorites page
- [x] Add a componentDidMount method that fetches the users favorites from the server and saves to state
- [x] Update favoritesList get route & remove unnecessary info
- [x] Update component to render a list of the users favorited exercises
- [x] Update logic for headerButton and headerHref variables
- [x] Add handleClick method for view exercise list button
- [x] Add click handler for the favorites list button in profile
