### ISSUE TITLE
User can filter exercises by body part

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#2]
## 💰 Feature

User can filter exercises by body part

## 🗒️ Notes

This will require me to use a drop down form, click event listeners, and fetch request

## 🖼 Wireframe

![filter-exercises](https://user-images.githubusercontent.com/68713535/102935009-1bdac680-445a-11eb-8d1f-d2d0981cac5f.png)

## ✅ Tasks

- [x] Input a few more data items to data.sql, at least one for each muscle group
- [x] Add a route to index.js that handles get requests for specific muscle groups.
- [x] Test the route with HTTPie
- [x] Add a handleChange method to the ExerciseList component that updates the exercises state when a filter option is clicked
