### ISSUE TITLE
User can view details of past logged workouts

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#20]
## 💰 Feature

User can view past logged workouts

## 🗒️ Notes

This will require me to use database, fetch, click listener

## 🖼 Wireframe

![past-logged-workout-details](https://user-images.githubusercontent.com/68713535/103426096-c2664c00-4b6b-11eb-95f6-ddc81418fa03.png)

## ✅ Tasks
- [x] Create a component that renders the workout-details page
- [x] Style to match wireframe
- [x] Update the server to include a route that handles get requests for workout info
- [x] test with HTTPie
- [x] Use a fetch request to get workout details and save to state
- [x] Refractor component to display data for each exercise
- [x] Add a click handler for the see full details button that renders the workout details component
- [x] Add a click handler for the back button to return to journal page.
- [x] Update getExerciseDetails method with map method
- [x] Move format date to server side
