### ISSUE TITLE
User can sign up

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#25]
## 💰 Feature

User can sign up

## 🗒️ Notes

This will require me to use forms, a new post route, password hashing and token authentication, hash routing

## 🖼 Wireframe

![landing-page](https://user-images.githubusercontent.com/68713535/103686958-6709d480-4f44-11eb-9f94-eb9052f04cc0.png)
![sign-up-page](https://user-images.githubusercontent.com/68713535/103686966-68d39800-4f44-11eb-975d-ed6eaf43644c.png)

## ✅ Tasks
- [x] Create a component that renders the landing page.
- [x] Implement hash routing 
- [x] Create a component that renders the sign up page
- [x] Create a route in the server that handles post requests to the users table. Test with HTTPie
- [x] Hash the password and save the user info to database
- [x] Add a handleChange method to the sign up form that updates state with user info
- [x] Add a handleSubmit method to the sign up form that sends the post method Fetch request to the server
