### ISSUE TITLE
User can log in

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#27]
## 💰 Feature

User can log in

## 🗒️ Notes

This will require me to use forms, a new server post route, hash routing, jwt

## 🖼 Wireframe

![login:home](https://user-images.githubusercontent.com/68713535/103716758-a6521880-4f78-11eb-9c88-c8eaa9893578.png)

## ✅ Tasks
- [x] Create a component that renders the login page
- [x] Add a hash route from login button on landing page and from sign up submit to the log in page.
- [x] Add a client-error file to the server.
- [x] Update server with a post route that verifies the users username and password. Test with HTTPie
- [x] Add a handleChange method to the login page that updates the state with username and password
- [x] Add a handleSubmit method that sends the fetch request to the server in a post request.
- [x] Create a component that renders the home page
- [x] Redirect the user to the home page after submitting log in using hash routing
