### ISSUE TITLE
User can view details of an exercise (how to + demo pic)

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#3]
## 💰 Feature

User can view details of an exercise (how to + demo pic)

## 🗒️ Notes

This will require me to use fetch requests, props, events in react.

## 🖼 Wireframe

![exercise_info_details](https://user-images.githubusercontent.com/68713535/102939609-6876cf80-4463-11eb-9b43-a5445a2c0bb8.png)

## ✅ Tasks
- [x] Add a conditional to your existing (2nd) route checking if the :id is greater than 1 character. 
- [x] Set up conditional to provide a different sql depending on the :id provided.
- [x] Test the route with HTTPie
- [x] Add a components folder and add an exercise-detail file to it
- [x] Define the component that renders a modal including the exercise name, demo image, and how to description.
- [x] Style Modal to match wireframe
- [x] Define a method that gets the exercise details for the modal and renders the ExerciseDetail component to the page
- [x] Pass the exercise information as a props to modal component.
- [x] Update the render method to check if a modal is open, if yes render the modal if not render the exercise list
- [x] Add a line break to the how to section for each number
