### ISSUE TITLE
User can add goals to profile

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#30]
## 💰 Feature

User can add goals
On profile there is a mini todo list where a user can add and check off goals

## 🗒️ Notes

This will require me to use fetch, todo list

## 🖼 Wireframe

![view-profile](https://user-images.githubusercontent.com/68713535/102942629-b9d68d00-446a-11eb-8a54-15190ffa84c1.png)

## ✅ Tasks
- [x] Create a component that renders the goals section and insert in profile component.
- [x] Separate goals form and list to their own components.
- [x] Add a route to the server that handles post requests to the goals table. test with httpie
- [x] Add a handleChange method to goals-form component that updates state with input
- [x] Add a handleSubmit method to the goals-form component that sends the post method fetch request and 
- [x] Define a server route that gets all user goals. test with httpie.
- [x] Add a componentDidMount method that sends a fetch request to the server for user goals and sets them to state.
- [x] Create an individual goal component that renders each goal.
- [x] Add a route to the server that patches the selected goal with the opposite completed value
- [x] Add a toggle completed method to the goals component
- [x] Update addGoal method so the new goal is pushed to a new array and state is updated with the new array of goals
- [x] Take out if statement in toggleCompleted method and return a boolean. 
- [x] Add authorization middleware file to server
- [x] reorganize server routes to use authorization middleware for every route except sign in, sign up, get exercises & get filtered exercises. Add headers with token for all requests needing auth
