### ISSUE TITLE
Fix Journal Bug

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#32]
## 🗒️ Notes

Determine if the workout is custom or not to decide how to display

## 🖼 Wireframe

![logged-workouts-journal](https://user-images.githubusercontent.com/68713535/103930755-175a1300-50d4-11eb-8b02-b573f54fab71.png)

## ✅ Tasks

- [x] Update database to include isCustom column with boolean value on the workouts table
- [x] Update server route to include custom workout info
- [x] Update renderLoggedWorkouts method to determine how the element should be displayed based on isCustom value
- [x] test all functionality again - fix all bugs
