### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#37]
## 💰 Feature

User can sign out

## 🗒️ Notes

This will require me to use local storage & context

## 🖼 Wireframe

![sign-out](https://user-images.githubusercontent.com/68713535/104079537-7bfe9600-51d8-11eb-9855-7b4ba4be4cc2.png)

## ✅ Tasks
- [x] Add a handleSignOut method to main app file
- [x] Save the method to context
- [x] Add a sign out button to the profile page with the onClick prop set to handleSignOut
- [x] Remove Add to favorites button on exercise list for now
