### ISSUE TITLE
User can log a workout

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#4]
## 💰 Feature

User can log a workout

## 🗒️ Notes

Log will include, date, duration, exercises, sets reps, weight.
This will require me to use forms, click listeners, fetch, database
## 🖼 Wireframe

![log_workout](https://user-images.githubusercontent.com/68713535/102940192-a0324700-4464-11eb-9dde-4bb96ce994a0.png)

## ✅ Tasks
- [x] Add a user to the users table in database
- [x] Add a route to the server that handles put requests to the database
- [x] Test the route with HTTPie
- [x] Restructure - give header its own component for re-use
- [x] Create a component that renders the first page of the log workout form.
- [x] Style to match wireframe
- [x] Add a handleChange method that updates the state with the user input
- [x] Add an handleSubmit method that sends the user data to the server in a put request
- [x] Update the handleSubmit method to change the view to add exercises page
- [x] Update exercise-list component to include an add button for each exercise
- [x] Update the getExercises method to check state.view to determine add button class
- [x] Update the handleClick method to check the tagName of the target
- [x] Create a components that renders the add button pop up if the click target was the add button
- [x] Style to match wireframe
- [x] Restructure - swap state.view for state.workoutId and save the workoutId as a prop in the exerciseList component
- [x] Add a method to ExerciseList that renders that add button pop-up
- [x] Update render method to check if that add button pop up should be rendered
- [x] Update render method so heading changes and the filter is hidden when the info or add box is shown
- [x] Add a route to the server that handles put requests which puts sets reps and weight into the sets table and inserts data to exerciseSets table
- [x] Test the route with HTTPie
- [x] Add a handleClick method to the add a set button that sends a fetch request to the server inserting the reps and weight data to the sets table and the workoutId, exerciseId, and setId to the exerciseSets table
- [x] Add a handleSubmit method that ends the log for that exercise, sending the user back to the add exerciseList
- [x] Add a finish button to end the log workout
- [x] Clean up code/test all functionality again
- [x] Remove props from state on add-exercise component
- [x] Update PUT routes/fetch requests to POST
- [x] Update inputs in add exercise with a name prop and restructure handleChange method to eliminate conditional.
- [x] Remove props.workoutId from state in exercise-list component
- [x] Update getInfoBox and getAddBox with find method rather than findIndex
- [x] Update determining addButtonClass with a ternary expression
- [x] Update inputs in log-workout-initial form to use name prop and restructure handleChange method in log-workout component to eliminate conditional.
- [x] Rename SQL variables
- [x] Update sets post route with a common table expression
- [x] Update styling
