### ISSUE TITLE
Polish Fit-Journey

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#40]
## 💰 Feature

Add a demo user so users do not need to log in to test app.  Update navigation/ mobile responsiveness

## ✅ Tasks

- [ ] Update database with more exercises.
- [ ] Add a demo user to database
- [ ] Delete need for email in user sign up
- [ ] Add a button to landing page that allows users to sign in with demo account
