### ISSUE TITLE
User can view list of past logged workouts

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#5]
## 💰 Feature

User can view past logged workouts

## 🗒️ Notes

This will require me to use database, fetch, click listener

## 🖼 Wireframe

![view-list-of-loggedworkouts](https://user-images.githubusercontent.com/68713535/103426036-5b489780-4b6b-11eb-83bf-83222f0f9371.png)

## ✅ Tasks

- [x] Create a component that renders the journal page
- [x] Style to match wireframe
- [x] Update the server to include a route that handles get requests for workout info
- [x] Test with HTTPie
- [x] Use a fetch request to get workout data when mounting and save to state
- [x] Create a method that renders the workout data for each workout
- [x] Update dates so that it reads month day, year
- [x] Update workout spacing and delete comments in index.js
