### ISSUE TITLE
User can log a custom entry

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#6]
## 💰 Feature

User can log a custom entry

## 🗒️ Notes

This will require me to use forms

## 🖼 Wireframe

![custom_entry](https://user-images.githubusercontent.com/68713535/102941751-551a3300-4468-11eb-8750-b98ffd008a5d.png)

## ✅ Tasks
- [x] Add a create custom entry button to the log workout initial form.
- [x] Create a component that renders the custom entry form
- [x] Style to match wireframe
- [x] Add a route to the server that handles post requests to the customWorkout table
- [x] Test with HTTPie & verify data is saved to database
- [x] Add a handleSubmit method that uses a fetch request to send the user data to the server
