### ISSUE TITLE
User can create a profile

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#7]
## 💰 Feature

User can Create a profile

## 🗒️ Notes

This will require me to use forms & file uploads

## 🖼 Wireframe

![create_profile](https://user-images.githubusercontent.com/68713535/102942450-35840a00-446a-11eb-8f1a-e4ff40bb009a.png)

## ✅ Tasks
- [x] Create a component that renders the create profile page
- [x] Add a route to the server that handles patch requests to the users table
- [x] Define a handleChange method that saves user inputed data to state
- [x] Define a handleSubmit method that sends a patch method fetch request to the server
- [x] Create an upload modal and add a click handler to the change picture button
- [x] Add file upload capability for profile picture
- [x] Add a renderProfilePicture method that updates the profile picture with the provided upload once its uploaded
