### ISSUE TITLE
User can view their profile/navigate through current app features

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#8]
## 💰 Feature

User can view profile.
On profile there is a mini todo list where a user can add and check off goals

## 🗒️ Notes

This will require me to use fetch, todo list

## 🖼 Wireframe

![view-profile](https://user-images.githubusercontent.com/68713535/102942629-b9d68d00-446a-11eb-8a54-15190ffa84c1.png)

## ✅ Tasks

- [x] Create a component that renders profile page
- [x] Create a route that handles get request for info in users table. Test with HTTPie.
- [x] Add a component did mount method that sends a fetch request for the users personal info from the db
- [x] Use logic to determine page rendered should be create profile or just profile.
- [x] Update hash routing to allow navigation
