### ISSUE TITLE
User can edit their profile

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/fit-journey#9]
## 💰 Feature

User can edit their profile.

## 🗒️ Notes

This will require me to use forms

## 🖼 Wireframe

![edit-profile](https://user-images.githubusercontent.com/68713535/102942728-f5715700-446a-11eb-98e7-99f1eff20f13.png)

## ✅ Tasks
- [x] Add an anchor tag to the profile page that links the the create-profile form
- [x] Update the name of the page to be less specific so it can be used for create and edit
- [x] Update create profile form to fetch user data when mounting and save to state so current info is presented
- [x] Add a placeholder profile picture div in case the user does not want to upload a picture
- [x] Change server get users route to return an object not an array
